export enum Stage {
  BEGIN = 'BEGIN',
  PREPARE_URL = 'PREPARE_URL',
  PREPARE_PARAMS = 'PREPARE_PARAMS',
  INIT_RESOURCE = 'INIT_RESOURCE',
  RESPONSE_BAD_RESULT = 'RESPONSE_BAD_RESULT',
  RESOLVE_VALUES = 'RESOLVE_VALUES',
  HTTP_REQUEST = 'HTTP_REQUEST',
  HTTP_RESPONSE = 'HTTP_RESPONSE',
  END = 'END'
}
