export enum Stage {
  BEGIN = 'BEGIN',
  PREPARE_URL = 'PREPARE_URL',
  INIT_RESOURCE = 'INIT_RESOURCE',
  RESOLVE_VALUES = 'RESOLVE_VALUES',
  HTTP_REQUEST = 'HTTP_REQUEST',
  HTTP_RESPONSE = 'HTTP_RESPONSE',
  END = 'END'
}
